name: Docker Image CI

on:
  push:
    branches:
      - main # This workflow runs on pushes to the 'main' branch

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} # Your Docker Hub username
  IMAGE_NAME: fsu-discord-bot # Name for your Docker image (e.g., your-repo-name)

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Action to check out your repository code

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # Action to log in to Docker Hub
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} # Use a GitHub Secret for your Docker Hub password

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5 # Action to build and push Docker images
        with:
          context: . # Build context is the root of the repository
          push: true # Push the image to Docker Hub
          tags: | # Define image tags
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest # latest tag
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} # Tag with commit SHA for unique versions
          cache-from: type=gha # Cache layers to speed up builds
          cache-to: type=gha,mode=max
